# SwiftPlaygroundsKit document generator jazzy settings

copyright: Copyright 2020 Sven Tiigi
author: Sven Tiigi
github_url: https://github.com/SvenTiigi/SwiftPlaygroundsCLI
xcodebuild_arguments: [-target, SwiftPlaygroundsKit]
clean: true
output: ./Documentation
min_acl: internal
